# Generated by Django 4.2.3 on 2023-07-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='item',
            name='Address',
            field=models.CharField(default='India', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='Location',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='Phone',
            field=models.IntegerField(default='11111111', max_length=13),
        ),
    ]
